// REACT/src/components/PageNotFound.js
import React from 'react';
import { Link } from 'react-router';

export default function PageNotFound() {
	return (
		<div className="column is-8">
			<div className="card ">
				<header className="card-header">
					<p className="card-header-title"> Error </p>
				</header>
				<div className="content">
					<div className="has-text-centered">
						<br /> <br /> <br />
						<p>This page does not exist.</p>
						<Link to="/"><span className="icon"><i className="fa fa-arrow-right"></i></span> go back to home.</Link>
						<br /> <br /> <br />
					</div>
				</div>
			</div>
		</div>
	);
}

// ANGULAR/src/app/shared/page-not-found/page-not-found.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cpa-page-not-found',
  templateUrl: './page-not-found.component.html',
  styles: []
})
export class PageNotFoundComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="card ">
    <header class="card-header">
        <p class="card-header-title"> Error </p>
    </header>
    <div class="content">
        <div class="has-text-centered">
            <br> <br> <br>
            <p>This page does not exist.</p>
            <a routerLink="/"><span class="icon"><i class="fa fa-arrow-right"></i></span> go back to home.</a>
            <br> <br> <br>
        </div>
    </div>
</div>
