// ANGULAR/src/app/shared/sidebar/sidebar.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'cpa-sidebar',
  templateUrl: './sidebar.component.html',
  styleUrls: ['./sidebar.component.css']
})
export class SidebarComponent implements OnInit {

  constructor() { }

  ngOnInit() {
  }

}

<div class="card">
	<div class="card-content">
		<aside class="menu">
			<p class="menu-label">
				General
			</p>
			<ul class="menu-list">
				<li><a routerLink="/contacts/new" routerLinkActive="is-active">Add new Contact</a></li>
				<li><a>Dashboard</a></li>
				<li><a>Customers</a></li>
			</ul>
			<p class="menu-label">
				Administration
			</p>
			<ul class="menu-list">
				<li><a>Team Settings</a></li>
				<li>
					<a class="is-active">Manage Your Team</a>
					<ul>
						<li><a>Members</a></li>
						<li><a>Plugins</a></li>
						<li><a>Add a member</a></li>
					</ul>
				</li>
				<li><a>Invitations</a></li>
				<li><a>Cloud Storage Environment Settings</a></li>
				<li><a>Authentication</a></li>
			</ul>
			<p class="menu-label">
				Transactions
			</p>
			<ul class="menu-list">
				<li><a>Payments</a></li>
				<li><a>Transfers</a></li>
				<li><a>Balance</a></li>
			</ul>
		</aside>
	</div>
</div>

// REACT/src/components/Sidebar.js
import React from 'react';
import { Link } from 'react-router';

export default function Sidebar() {
	return (
		<div className="column is-4 is-hidden-mobile">
			<div className="card">
				<div className="card-content">
					<aside className="menu">
						<p className="menu-label">
							General
								</p>
						<ul className="menu-list">
							<li><Link to="/contacts/new" activeClassName="is-active">Add new Contact</Link></li>
							<li><a>Dashboard</a></li>
							<li><a>Customers</a></li>
						</ul>
						<p className="menu-label">
							Administration
								</p>
						<ul className="menu-list">
							<li><a>Team Settings</a></li>
							<li>
								<a className="is-active">Manage Your Team</a>
								<ul>
									<li><a>Members</a></li>
									<li><a>Plugins</a></li>
									<li><a>Add a member</a></li>
								</ul>
							</li>
							<li><a>Invitations</a></li>
							<li><a>Cloud Storage Environment Settings</a></li>
							<li><a>Authentication</a></li>
						</ul>
						<p className="menu-label">
							Transactions
								</p>
						<ul className="menu-list">
							<li><a>Payments</a></li>
							<li><a>Transfers</a></li>
							<li><a>Balance</a></li>
						</ul>
					</aside>
				</div>
			</div>
		</div>
	);
}
